export const countries =[
    {id:208, name:"Türkiye"},
    {id:1, name:"Bangladeş"},
    {id:2, name:"Belçika"},
    {id:3, name:"Burkina Faso"},
    {id:4, name:"Bulgaristan"},
    {id:5, name:"Bosna Hersek"},
    {id:6, name:"Barbados"},
    {id:7, name:"Wallis ve Futuna"},    
    {id:8, name:"Saint Barthelemy"},
    {id:9, name:"Bermuda"},
    {id:10, name:"Brunei"},
    {id:11, name:"Bolivya"},
    {id:12, name:"Bahreyn"},
    {id:13, name:"Burundi"},
    {id:14, name:"Benin"},
    {id:15, name:"Butan"},
    {id:16, name:"Jamaika"},
    {id:17, name:"Bouvet Adası"},
    {id:18, name:"Botsvana"},
    {id:19, name:"Samoa"},
    {id:20, name:"Bonaire, Saint Eustatius ve Saba"},
    {id:21, name:"Brezilya"},
    {id:22, name:"Bahamalar"},
    {id:23, name:"Jersey"},
    {id:24, name:"Beyaz Rusya"},
    {id:25, name:"Belize"},
    {id:26, name:"Rusya"},
    {id:27, name:"Ruanda"},
    {id:28, name:"Sırbistan"},
    {id:29, name:"Doğu Timor"},
    {id:30, name:"Réunion"},
    {id:31, name:"Türkmenistan"},
    {id:32, name:"Tacikistan"},
    {id:33, name:"Romanya"},
    {id:34, name:"Tokelau"},
    {id:35, name:"Gine-Bissau"},
    {id:36, name:"Guam"},
    {id:37, name:"Guatemala"},
    {id:38, name:"Güney Georgia ve Güney Sandviç Adaları"},
    {id:39, name:"Yunanistan"},
    {id:40, name:"Ekvator Ginesi"},
    {id:41, name:"Guadeloupe"},
    {id:42, name:"Japonya"},
    {id:43, name:"Guyana"},
    {id:44, name:"Guernsey"},
    {id:45, name:"Fransız Guyanası"},
    {id:46, name:"Gürcistan"},
    {id:47, name:"Grenada"},
    {id:48, name:"Birleşik Krallık"},
    {id:49, name:"Gabon"},
    {id:50, name:"El Salvador"},
    {id:51, name:"Gine"},
    {id:52, name:"Gambiya"},
    {id:53, name:"Grönland"},
    {id:54, name:"Cebelitarık"},
    {id:55, name:"Gana"},
    {id:56, name:"Umman"},
    {id:57, name:"Tunus"},
    {id:58, name:"Ürdün"},
    {id:59, name:"Hırvatistan"},
    {id:60, name:"Haiti"},
    {id:61, name:"Macaristan"},
    {id:62, name:"Hong Kong"},
    {id:63, name:"Honduras"},
    {id:64, name:"Heard Adası ve McDonald Adaları"},
    {id:65, name:"Venezüella"},
    {id:66, name:"Porto Riko"},
    {id:67, name:"Palau"},
    {id:68, name:"Portekiz"},
    {id:69, name:"Svalbard"},
    {id:70, name:"Paraguay"},
    {id:71, name:"Irak"},
    {id:72, name:"Panama"},
    {id:73, name:"Fransız Polinezyası"},
    {id:74, name:"Papua Yeni Gine"},
    {id:75, name:"Peru"},
    {id:76, name:"Pakistan"},
    {id:77, name:"Filipinler"},
    {id:78, name:"Pitcairn Adaları"},
    {id:79, name:"Polonya"},
    {id:80, name:"Saint Pierre ve Miquelon"},
    {id:81, name:"Zambiya"},
    {id:82, name:"Batı Sahra"},
    {id:83, name:"Estonya"},
    {id:84, name:"Mısır"},
    {id:85, name:"Güney Afrika"},
    {id:86, name:"Ekvador"},
    {id:87, name:"İtalya"},
    {id:88, name:"Vietnam"},
    {id:89, name:"Solomon Adaları"},
    {id:90, name:"Etiyopya"},
    {id:91, name:"Somali"},
    {id:92, name:"Zimbabwe"},
    {id:93, name:"Suudi Arabistan"},
    {id:94, name:"İspanya"},
    {id:95, name:"Eritrea"},
    {id:96, name:"Karadağ"},
    {id:97, name:"Moldova"},
    {id:98, name:"Madagaskar"},
    {id:99, name:"Saint Martin"},
    {id:100, name:"Fas"},
    {id:101, name:"Monaco"},
    {id:102, name:"Özbekistan"},
    {id:103, name:"Myanmar"},
    {id:104, name:"Mali"},
    {id:105, name:"Macao"},
    {id:106, name:"Moğolistan"},
    {id:107, name:"Marshall Adaları"},
    {id:108, name:"Makedonya"},
    {id:109, name:"Mauritius"},
    {id:110, name:"Malta"},
    {id:111, name:"Malavi"},
    {id:112, name:"Maldivler"},
    {id:113, name:"Martinik"},
    {id:114, name:"Kuzey Mariana Adaları"},
    {id:115, name:"Montserrat"},
    {id:116, name:"Moritanya"},
    {id:117, name:"Isle of Man"},
    {id:118, name:"Uganda"},
    {id:119, name:"Tanzanya"},
    {id:120, name:"Malezya"},
    {id:121, name:"Meksika"},
    {id:122, name:"İsrail"},
    {id:123, name:"Fransa"},
    {id:124, name:"İngiliz Hint Okyanusu Bölgesi"},
    {id:125, name:"Saint Helena"},
    {id:126, name:"Finlandiya"},
    {id:127, name:"Fiji"},
    {id:128, name:"Falkland Adaları"},
    {id:129, name:"Mikronezya"},
    {id:130, name:"Faroe Adaları"},
    {id:131, name:"Nikaragua"},
    {id:132, name:"Hollanda"},
    {id:133, name:"Norveç"},
    {id:134, name:"Namibya"},
    {id:135, name:"Vanuatu"},
    {id:136, name:"Yeni Kaledonya"},
    {id:137, name:"Nijer"},
    {id:138, name:"Norfolk Adası"},
    {id:139, name:"Nijerya"},
    {id:140, name:"Yeni Zelanda"},
    {id:141, name:"Nepal"},
    {id:142, name:"Nauru"},
    {id:143, name:"Niue"},
    {id:144, name:"Cook Adaları"},
    {id:145, name:"Kosova"},
    {id:146, name:"Fildişi Sahilleri"},
    {id:147, name:"İsviçre"},
    {id:148, name:"Kolombiya"},
    {id:149, name:"Çin"},
    {id:150, name:"Kamerun"},
    {id:151, name:"Şili"},
    {id:152, name:"Cocos Adaları"},
    {id:153, name:"Kanada"},
    {id:154, name:"Kongo Cumhuriyeti"},
    {id:155, name:"Orta Afrika Cumhuriyeti"},
    {id:156, name:"Demokratik Kongo Cumhuriyeti"},
    {id:157, name:"Çek Cumhuriyeti"},
    {id:158, name:"Kıbrıs"},
    {id:159, name:"Noel Adası"},
    {id:160, name:"Kosta Rika"},
    {id:161, name:"Curacao"},
    {id:162, name:"Cape Verde"},
    {id:163, name:"Küba"},
    {id:164, name:"Svaziland"},
    {id:165, name:"Suriye"},
    {id:166, name:"Sint Maarten"},
    {id:167, name:"Kırgızistan"},
    {id:168, name:"Kenya"},
    {id:169, name:"Güney Sudan"},
    {id:170, name:"Surinam"},
    {id:171, name:"Kiribati"},
    {id:172, name:"Kamboçya"},
    {id:173, name:"Saint Kitts ve Nevis"},
    {id:174, name:"Komor"},
    {id:175, name:"Sao Tome ve Principe"},
    {id:176, name:"Slovakya"},
    {id:177, name:"Güney Kore"},
    {id:178, name:"Slovenya"},
    {id:179, name:"Kuzey Kore"},
    {id:180, name:"Kuveyt"},
    {id:181, name:"Senegal"},
    {id:182, name:"San Marino"},
    {id:183, name:"Sierra Leone"},
    {id:184, name:"Seyşel Adaları"},
    {id:185, name:"Kazakistan"},
    {id:186, name:"Kayman Adaları"},
    {id:187, name:"Singapur"},
    {id:188, name:"İsveç"},
    {id:189, name:"Sudan"},
    {id:190, name:"Dominik Cumhuriyeti"},
    {id:191, name:"Dominika"},
    {id:192, name:"Cibuti"},
    {id:193, name:"Danimarka"},
    {id:194, name:"İngiliz Virgin Adaları"},
    {id:195, name:"Almanya"},
    {id:196, name:"Yemen"},
    {id:197, name:"Cezayir"},
    {id:198, name:"Amerika Birleşik Devletleri"},
    {id:199, name:"Uruguay"},
    {id:200, name:"Mayotte"},
    {id:201, name:"Birleşik Devletlerin Küçük Dış Adaları"},
    {id:202, name:"Lübnan"},
    {id:203, name:"Saint Lucia"},
    {id:204, name:"Laos"},
    {id:205, name:"Tuvalu"},
    {id:206, name:"Tayvan"},
    {id:207, name:"Trinidad ve Tobago"},    
    {id:209, name:"Sri Lanka"},
    {id:210, name:"Lihtenştayn"},
    {id:211, name:"Letonya"}
  ]